server:
  port: 8080

spring:
  # Application
  application:
    name: NinSite

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5431/NiN
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Liquibase
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    user: postgres
    password: postgres

  # Hibernate
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nikchemno.nesmachno@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.eclipse.angus.mail: DEBUG
    org.springframework.mail: DEBUG

app:
  mail:
    from: "NiN <nikchemno.nesmachno@gmail.com>"
  public-base-url: "http://localhost:8080"

  # Media config
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

# Identity token security
jwt:
  secret: "dev-secret-change-measdasdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"

security:
  refresh:
    ttl-days: 14
    bytes: 64
    pepper: "CHANGE_ME_LONG_RANDOM"

# Media config
media:
  storage:
    local:
      root: ./storage/media
  limits:
    max-size-bytes: 104857600