server:
  port: 8080

spring:
  # Application
  application:
    name: NinSite

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5431/NiN
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Liquibase
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nikchemno.nesmachno@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: [openid, profile, email]
            authorization-grant-type: authorization_code
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
#          github:
#            redirect-uri: http://localhost:8080/login/oauth2/code/github
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
#            scope: read:user, user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: id
  # Media config
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

# Logging
logging:
  level:
#    org.springframework.security: DEBUG
    org.eclipse.angus.mail: DEBUG
    org.springframework.mail: DEBUG
    ua.nin: DEBUG
    root: INFO

    # Security chain, matchers, decisions, auth failures
    org.springframework.security: TRACE

    # MVC dispatching, handler mapping, exception resolvers
    org.springframework.web: TRACE
    org.springframework.web.servlet: TRACE

    # Filter registration/order at startup
    web: DEBUG

app:
  mail:
    from: "NiN <nikchemno.nesmachno@gmail.com>"
  public-base-url: "http://localhost:8080"

# Identity token security
jwt:
  secret: ${JWT_SECRET}
  secret-base64: ${JWT_SECRET_BASE64:false}
  issuer: ${JWT_ISSUER:NiN}
  access-ttl-minutes: ${JWT_ACCESS_TTL_MINUTES}

security:
  refresh:
    ttl-days: 14
    secure: false
  ott:
    bytes: 32
    pepper: ${OTT_PEPPER}
  email-verify:
    ttl-minutes: 30
  password-reset:
    ttl-minutes: 30

# Media config
media:
  storage:
    local:
      root: ./storage/media
  limits:
    max-size-bytes: 104857600